name: "Draft Release"

on:
  push:
  workflow_dispatch:

jobs:
# Generate patch version number
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Read major.minor
        id: majmin
        run: |
          VER=$(cat ./version.txt)
          echo ${VER}
          echo "::set-output name=version::${VER}"
# Create or update Draft release
      - name: Build and test
        run: |
          echo "done!"
      - name: Insert patch number
        run: |
          sed -i "/∆version ← '[0-9]\+.[0-9]\+-\?[a-z]\+\?.0'/s/.0'/.${{ github.run_number }}-${{ github.sha }}'/" MyTool.dyalog
          cat MyTool.dyalog
      - name: Draft release
        uses: "marvinpinto/action-automatic-releases@latest"        
        with:
         # ver: ${{ cat 'version.txt' }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.majmin.outputs.version }}.${{ github.run_number }}-${{ github.sha }}"
          prerelease: false
          draft: true
          title: "v${{ steps.majmin.outputs.version }}.${{ github.run_number }}"
          files: |
            MyTool.dyalog

